site_name: DemaTrading.ai
nav:
    - Home: home.md
    - Making Money: makingmoney.md
    - Quickstart: quickstart.md
    - Strategy Examples: strategyexamples.md
    - Definitions/FAQ: definitionsfaq.md
    - Changelog: changelog.md
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css